//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class local_authority_data
    {
        public int id { get; set; }
        public string local_authority { get; set; }
        public string postcode_area { get; set; }
        public decimal percentage_not_receiving_2mbs { get; set; }
        public decimal average_sync_speed_mBits { get; set; }
        public decimal superfast_broadband_availability { get; set; }
    }
}
