//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class postcode_speed
    {
        public int id { get; set; }
        public string postcode { get; set; }
        public Nullable<decimal> average_speed_mbps { get; set; }
        public Nullable<decimal> median_speed_mbps { get; set; }
        public Nullable<decimal> max_speed_mbps { get; set; }
        public string lines_less_than_2mbps { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public Nullable<int> county_id_fk { get; set; }
    
        public virtual county county { get; set; }
    }
}
