//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class school_performance
    {
        public int id { get; set; }
        public string school_name { get; set; }
        public string town { get; set; }
        public string postcode { get; set; }
        public decimal percent_5_pass_grades_gcse { get; set; }
        public decimal percent_7_pass_grades_maths_english { get; set; }
        public decimal percent_entitled_free_meals { get; set; }
        public Nullable<int> county_id_fk { get; set; }
    
        public virtual county county { get; set; }
    }
}
